# Generated by Django 2.1.7 on 2019-05-26 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='is_worked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 5, 26)),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='ended_date',
            field=models.DateField(),
        ),
    ]
