# Generated by Django 2.1.7 on 2019-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='is_worked',
            field=models.BooleanField(default=True),
        ),
    ]
