# Generated by Django 2.1.7 on 2019-05-21 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_uploadmodel_is_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 5, 22)),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='ended_date',
            field=models.DateField(),
        ),
    ]
