# Generated by Django 2.1.7 on 2019-05-24 12:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_auto_20190522_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 5, 24)),
        ),
    ]
